server:
  port: ${PORT:8761}

eureka:
  instance:
    hostname: peer0
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:8762/eureka
  server:
    wait-time-in-ms-when-sync-empty: 0
    
---
spring:
  profiles: peer1

server:
  port: 8762
  
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:8763/eureka
  
---
spring:
  profiles: peer2

server:
  port: 8763
  
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:8762/eureka
