server:
  port: ${PORT:8081}

security:
  basic:
    enabled: false

zuul:
  routes:
    produto:
      path: /client-produto/**
      serviceId: PRODUTO-SERVICE
    orcamento:
      path: /client-orcamento/**
      serviceId: ORCAMENTO-SERVICE
      
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000