spring:
  application:
    name: auth-service
  data:
    mongodb:
      database: auth

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          configuration:
            key:
              serializer: org.apache.kafka.common.serialization.StringSerializer
      bindings:
        momentsUserChanged:
          destination: moments.user.changed
          contentType: application/json
server:
  port: 9000

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true


security:
  basic:
    enable: false

  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: 5f9f7765e428e9500296fead15b93435

  service:
    username: d245ef53-5ad5-4216-9c56-89fe0f8302a0
    password: ef919ae4-b893-4969-b782-57978180ad33